export const API_PATHS = {
  health: '/api/v1/health',
  appRuntime: '/api/v1/app/runtime',
  appRecentWorkspaces: '/api/v1/app/workspaces/recent',
  appCurrentWorkspace: '/api/v1/app/workspaces/current',
  appOpenWorkspace: '/api/v1/app/workspaces/open',
  appSwitchWorkspace: '/api/v1/app/workspaces/switch',
  appWorkspace: (workspaceId) => `/api/v1/app/workspaces/${encodeURIComponent(workspaceId)}`,
  sessions: '/api/v1/sessions',
  sessionsList: (limit = 50) => `/api/v1/sessions?limit=${encodeURIComponent(limit)}`,
  sessionMessages: (sessionId, limit = 100) => `/api/v1/sessions/${encodeURIComponent(sessionId)}/messages?limit=${encodeURIComponent(limit)}`,
  sessionEvents: (sessionId, limit = 200) => `/api/v1/sessions/${encodeURIComponent(sessionId)}/events?limit=${encodeURIComponent(limit)}`,
  session: (sessionId) => `/api/v1/sessions/${encodeURIComponent(sessionId)}`,
  tasksStream: '/api/v1/tasks/stream',
  authSetup: '/api/v1/auth/setup',
  authLogin: '/api/v1/auth/login',
  authMe: '/api/v1/auth/me',
  authLogout: '/api/v1/auth/logout',
  devicesPair: '/api/v1/auth/devices/pair',
  deviceVerify: (deviceId) => `/api/v1/auth/devices/${encodeURIComponent(deviceId)}/verify`,
  deviceHeartbeat: (deviceId) => `/api/v1/auth/devices/${encodeURIComponent(deviceId)}/heartbeat`,
  todos: (limit = 100, sessionId = '') => `/api/v1/todos?limit=${encodeURIComponent(limit)}${sessionId ? `&sessionId=${encodeURIComponent(sessionId)}` : ''}`,
  logSources: '/api/v1/logs/sources',
  logsQuery: (limit = 120) => `/api/v1/logs/query?limit=${encodeURIComponent(limit)}`,
  runtimeConfig: '/api/v1/config/runtime',
  localHealth: (deep = false) => `/api/v1/config/local/health?deep=${deep ? 'true' : 'false'}`,
  configModels: '/api/v1/config/models',
};
