export const API_PATHS: {
  health: string;
  appRuntime: string;
  appRecentWorkspaces: string;
  appCurrentWorkspace: string;
  appOpenWorkspace: string;
  appSwitchWorkspace: string;
  appWorkspace: (workspaceId: string) => string;
  sessions: string;
  sessionsList: (limit?: number) => string;
  sessionMessages: (sessionId: string, limit?: number) => string;
  sessionEvents: (sessionId: string, limit?: number) => string;
  session: (sessionId: string) => string;
  tasksStream: string;
  authSetup: string;
  authLogin: string;
  authMe: string;
  authLogout: string;
  devicesPair: string;
  deviceVerify: (deviceId: string) => string;
  deviceHeartbeat: (deviceId: string) => string;
  todos: (limit?: number, sessionId?: string) => string;
  logSources: string;
  logsQuery: (limit?: number) => string;
  runtimeConfig: string;
  localHealth: (deep?: boolean) => string;
  configModels: string;
};
